version: "3.0"

services:
    phpmyadmin:
        depends_on: 
            - db
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks: 
            - php_ricemeal_network
    db:
        image: mysql:5.7
        ports: 
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: toor
            MYSQL_DATABASE: ecom
            MYSQL_USER: ecom_usr
            MYSQL_PASSWORD: 1234
        volumes:
            - ./sql:/var/lib/mysql
        networks: 
            - php_ricemeal_network

networks:
    php_ricemeal_network: